---
- name: Executing OS specific tasks (Debian)
  include: "{{ ansible_os_family|lower }}.yml"
  when: ansible_os_family == 'Debian'

- name: Executing OS specific tasks (RedHat)
  include: "{{ ansible_os_family|lower }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Executing configuration tasks
  include: configure.yml
...
